#!/usr/bin/env python3
"""
TrailDiscover Build Pipeline
=============================
Single tool that runs the full build pipeline for TrailDiscover:

  1. format     – Normalize JSON formatting of all event files
  2. redact     – Redact sensitive data from .json.cloudtrail files
  3. copy-logs  – Copy .json.cloudtrail files to docs/logExamples
  4. generate   – Generate events.json, events.csv, datadog_dashboard.json, and the
                 ATT&CK files used by the Insights page (attack-index.json, attack-layer.json)

Usage:
    python build.py                  # Run all steps
    python build.py --steps format redact copy-logs generate
    python build.py --steps format   # Run only formatting
    python build.py --on-the-wild-only  # Dashboard only with wild events
    python build.py --tactics "TA0003 - Persistence" "TA0040 - Impact"
"""

import argparse
import csv
import hashlib
import json
import os
import re
import shutil
import sys
from typing import Any, List, Optional

# ---------------------------------------------------------------------------
# Paths (relative to this script, which lives in tools/)
# ---------------------------------------------------------------------------
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
EVENTS_DIR = os.path.join(ROOT_DIR, "events")
DOCS_DIR = os.path.join(ROOT_DIR, "docs")
LOG_EXAMPLES_DIR = os.path.join(DOCS_DIR, "logExamples")
EVENTS_JSON = os.path.join(DOCS_DIR, "events.json")
EVENTS_CSV = os.path.join(DOCS_DIR, "events.csv")
DASHBOARD_JSON = os.path.join(DOCS_DIR, "datadog_dashboard.json")
ATTACK_INDEX_JSON = os.path.join(DOCS_DIR, "attack-index.json")
ATTACK_LAYER_JSON = os.path.join(DOCS_DIR, "attack-layer.json")

# ATT&CK release the catalogue is mapped to. The lookup is generated by updateAttackLookup.py.
# Keep in step with ATTACK_VERSION in docs/shared.js (used for the site's ATT&CK links).
ATTACK_VERSION = "18.1"
ATTACK_LOOKUP = os.path.join(SCRIPT_DIR, "attack", f"enterprise-attack-{ATTACK_VERSION}-lookup.json")
SITE_URL = "https://traildiscover.cloud/"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def iter_event_files(extension: str = ".json"):
    """Yield (full_path, filename) for every file matching *extension* under EVENTS_DIR."""
    for root, _dirs, files in os.walk(EVENTS_DIR):
        for fname in sorted(files):
            if fname.endswith(extension) and not fname.endswith(".json.cloudtrail"):
                if extension == ".json":
                    yield os.path.join(root, fname), fname
            elif extension == ".json.cloudtrail" and fname.endswith(".json.cloudtrail"):
                yield os.path.join(root, fname), fname


# =====================================================================
# STEP 1 – Format
# =====================================================================

def step_format():
    """Re-write every .json event file with consistent 4-space indentation."""
    print("\n[ Step 1/4 ] Formatting event JSON files …")
    count = 0
    for fpath, _ in iter_event_files(".json"):
        with open(fpath, "r", encoding="utf-8") as fh:
            data = json.load(fh)
        with open(fpath, "w", encoding="utf-8") as fh:
            json.dump(data, fh, indent=4)
            fh.write("\n")
        count += 1
    print(f"  ✓ Formatted {count} event files.")


# =====================================================================
# STEP 2 – Redact CloudTrail logs
# =====================================================================

PLACEHOLDERS = {
    "accountId": "111111111111",
    "recipientAccountId": "111111111111",
    "accessKeyId": "AKIA****************",
    "principalId": "AROA****************:User",
    "sourceIPAddress": "0.0.0.0",
    "ip": "0.0.0.0",
}
IP_REGEX = re.compile(r"\b\d{1,3}(?:\.\d{1,3}){3}\b")
ACCOUNT_REGEX = re.compile(r"arn:aws:[a-z0-9-]+::(\d{12}):")
SENSITIVE_KEYS = set(PLACEHOLDERS.keys())


def _redact_value(key: str, value: Any) -> Any:
    if value is None:
        return value
    if key in PLACEHOLDERS:
        return PLACEHOLDERS[key]
    if isinstance(value, str):
        value = IP_REGEX.sub(PLACEHOLDERS["sourceIPAddress"], value)
        def _acct_sub(m):
            return m.group(0).replace(m.group(1), PLACEHOLDERS["accountId"])
        value = ACCOUNT_REGEX.sub(_acct_sub, value)
    return value


def _walk_redact(obj: Any):
    if isinstance(obj, dict):
        for k in list(obj.keys()):
            v = obj[k]
            if isinstance(v, (dict, list)):
                _walk_redact(v)
            else:
                obj[k] = _redact_value(k, v)
    elif isinstance(obj, list):
        for i in range(len(obj)):
            v = obj[i]
            if isinstance(v, (dict, list)):
                _walk_redact(v)
            else:
                obj[i] = _redact_value("value", v)


def step_redact():
    """Redact sensitive information from all .json.cloudtrail files."""
    print("\n[ Step 2/4 ] Redacting CloudTrail log files …")
    modified = []
    for fpath, _ in iter_event_files(".json.cloudtrail"):
        try:
            with open(fpath, "r", encoding="utf-8") as fh:
                data = json.loads(fh.read().strip())
        except Exception:
            continue
        original = json.dumps(data, sort_keys=True)
        _walk_redact(data)
        redacted = json.dumps(data, sort_keys=True)
        if redacted != original:
            with open(fpath, "w", encoding="utf-8") as fh:
                json.dump(data, fh, indent=4)
                fh.write("\n")
            modified.append(fpath)
    print(f"  ✓ Redacted {len(modified)} CloudTrail files.")
    for m in modified:
        print(f"    - {os.path.relpath(m, ROOT_DIR)}")


# =====================================================================
# STEP 3 – Copy CloudTrail logs to docs/logExamples
# =====================================================================

def step_copy_logs():
    """Copy all .json.cloudtrail files into docs/logExamples/."""
    print("\n[ Step 3/4 ] Copying CloudTrail logs to docs/logExamples …")
    os.makedirs(LOG_EXAMPLES_DIR, exist_ok=True)
    count = 0
    for fpath, fname in iter_event_files(".json.cloudtrail"):
        dest = os.path.join(LOG_EXAMPLES_DIR, fname)
        shutil.copy2(fpath, dest)
        count += 1
    print(f"  ✓ Copied {count} CloudTrail log files.")


# =====================================================================
# STEP 4 – Generate events.json, events.csv and datadog_dashboard.json
# =====================================================================

def _load_all_events() -> List[dict]:
    """Load every .json event file into a list."""
    events = []
    for fpath, _ in iter_event_files(".json"):
        with open(fpath, "r", encoding="utf-8") as fh:
            events.append(json.load(fh))
    return events


# --- events.json (for the web) -----------------------------------------

def _generate_events_json(events: List[dict]):
    with open(EVENTS_JSON, "w", encoding="utf-8") as fh:
        json.dump(events, fh, indent=4)
        fh.write("\n")
    print(f"  ✓ Generated {os.path.relpath(EVENTS_JSON, ROOT_DIR)} ({len(events)} events)")


# --- events.csv --------------------------------------------------------

CSV_HEADERS = [
    "eventName", "eventSource", "awsService", "description",
    "mitreAttackTactics", "mitreAttackTechniques", "mitreAttackSubTechniques",
    "usedInWild", "incidents", "researchLinks", "securityImplications",
    "alerting", "simulation", "permissions", "unverifiedMitreAttackTechniques",
]


def _generate_events_csv(events: List[dict]):
    with open(EVENTS_CSV, "w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=CSV_HEADERS)
        writer.writeheader()
        for event in events:
            row = dict(event)
            row["mitreAttackTactics"] = ", ".join(row.get("mitreAttackTactics", []))
            row["mitreAttackTechniques"] = ", ".join(row.get("mitreAttackTechniques", []))
            row["mitreAttackSubTechniques"] = ", ".join(row.get("mitreAttackSubTechniques", []))
            row["incidents"] = json.dumps(row.get("incidents", []))
            row["researchLinks"] = json.dumps(row.get("researchLinks", []))
            row["alerting"] = json.dumps(row.get("alerting", []))
            row["simulation"] = json.dumps(row.get("simulation", []))
            row["unverifiedMitreAttackTechniques"] = json.dumps(row.get("unverifiedMitreAttackTechniques", []))
            writer.writerow(row)
    print(f"  ✓ Generated {os.path.relpath(EVENTS_CSV, ROOT_DIR)}")


# --- Datadog dashboard -------------------------------------------------

TACTIC_ORDER = {
    "TA0001 - Initial Access": 1,
    "TA0002 - Execution": 2,
    "TA0003 - Persistence": 3,
    "TA0004 - Privilege Escalation": 4,
    "TA0005 - Defense Evasion": 5,
    "TA0006 - Credential Access": 6,
    "TA0007 - Discovery": 7,
    "TA0008 - Lateral Movement": 8,
    "TA0009 - Collection": 9,
    "TA0011 - Command and Control": 10,
    "TA0010 - Exfiltration": 11,
    "TA0040 - Impact": 12,
}


def _group_events_by_tactics(events, filter_tactics=None):
    tactics = {}
    for event in events:
        for tactic in event.get("mitreAttackTactics", []):
            if filter_tactics and tactic not in filter_tactics:
                continue
            tactics.setdefault(tactic, []).append(event)
    return tactics


def _exploited_event_names(events):
    return [e["eventName"] for e in events if e.get("usedInWild", False)]


def _dd_base():
    return {
        "title": "TrailDiscover AWS Events Insights",
        "description": "",
        "widgets": [],
        "layout_type": "ordered",
        "template_variables": [
            {"name": "userIdentity.arn", "prefix": "@userIdentity.arn", "available_values": [], "default": "*"},
            {"name": "network.client.ip", "prefix": "@network.client.ip", "available_values": [], "default": "*"},
            {"name": "account", "prefix": "account", "available_values": [], "default": "*"},
        ],
        "notify_list": [],
        "reflow_type": "fixed",
    }


def _dd_logo():
    return {
        "id": 2066777487,
        "definition": {
            "type": "image", "url": "https://traildiscover.cloud/logo.png",
            "sizing": "contain", "margin": "md", "has_background": False,
            "has_border": False, "vertical_align": "center", "horizontal_align": "center",
        },
        "layout": {"x": 0, "y": 0, "width": 6, "height": 2},
    }


def _dd_description():
    return {
        "id": 2066777488,
        "definition": {
            "type": "note",
            "content": (
                " # [TrailDiscover](https://traildiscover.cloud/)\n\n"
                "This dashboard, built using data from traildiscover.cloud, offers a detailed "
                "visualization of AWS CloudTrail events that have been utilized or are potentially "
                "used by attackers. Events are organized according to MITRE ATT&CK tactics. Each "
                "event is presented with two widgets: one provides a description, a direct link to "
                "traildiscover.cloud, and references to related incidents and research; the other "
                "features a counter displaying the frequency of these events in your AWS environment."
            ),
            "background_color": "white", "font_size": "14", "text_align": "left",
            "vertical_align": "top", "show_tick": False, "tick_pos": "50%",
            "tick_edge": "left", "has_padding": True,
        },
        "layout": {"x": 0, "y": 2, "width": 6, "height": 3},
    }


def _dd_top_ten(names):
    return {
        "id": 2985843941260464,
        "definition": {
            "title": "Top 10 CloudTrail Events exploited in the wild",
            "title_size": "16", "title_align": "left", "type": "toplist",
            "requests": [{
                "queries": [{
                    "data_source": "logs", "name": "query1", "indexes": ["*"],
                    "compute": {"aggregation": "count"},
                    "group_by": [{"facet": "@evt.name", "limit": 10, "sort": {"order": "desc", "aggregation": "count"}}],
                    "search": {"query": f"source:cloudtrail @evt.name:({' OR '.join(names)}) $userIdentity.arn $network.client.ip $account"},
                }],
                "response_format": "scalar",
            }],
            "style": {"display": {"type": "stacked", "legend": "automatic"}},
        },
        "layout": {"x": 0, "y": 0, "width": 6, "height": 2},
    }


def _dd_timeline(tactics):
    formulas, queries = [], []
    for idx, (tactic, events) in enumerate(tactics.items(), start=1):
        names = [e["eventName"] for e in events]
        formulas.append({"alias": tactic, "formula": f"query{idx}"})
        queries.append({
            "data_source": "logs", "name": f"query{idx}", "indexes": ["*"],
            "compute": {"aggregation": "count"},
            "search": {"query": f"source:cloudtrail @evt.name:({' OR '.join(names)}) $userIdentity.arn $network.client.ip $account"},
            "group_by": [], "storage": "hot",
        })
    return {
        "id": 8265946211738036,
        "definition": {
            "title": "MITRE ATT&CK Tactics Events Timeline",
            "title_size": "16", "title_align": "left",
            "show_legend": True, "legend_layout": "auto",
            "legend_columns": ["avg", "min", "max", "value", "sum"],
            "time": {}, "type": "timeseries",
            "requests": [{
                "formulas": formulas, "queries": queries,
                "response_format": "timeseries",
                "style": {"palette": "dog_classic", "line_type": "solid", "line_width": "normal"},
                "display_type": "bars",
            }],
        },
        "layout": {"x": 0, "y": 2, "width": 6, "height": 2},
    }


def _dd_tactic_widgets(event, tactic, x, y):
    note_content = (
        f"### [{event['eventName']}](https://traildiscover.cloud/#{event['awsService']}-{event['eventName']})\n\n"
        f"**Description:** {event['description']}\n\n"
    )
    if event.get("incidents"):
        note_content += "**Related Incidents:**\n" + "".join(
            f"- [{i['description']}]({i['link']})\n" for i in event["incidents"]
        )
    if event.get("researchLinks"):
        note_content += "**Related Research:**\n" + "".join(
            f"- [{r['description']}]({r['link']})\n" for r in event["researchLinks"]
        )
    note = {
        "id": hash((tactic, event["eventName"], "note")) & 0xFFFFFFFF,
        "definition": {
            "type": "note", "content": note_content,
            "background_color": "white", "font_size": "14",
            "text_align": "left", "vertical_align": "top",
            "show_tick": False, "has_padding": True,
        },
        "layout": {"x": x, "y": y, "width": 2, "height": 2},
    }
    query = {
        "id": hash((tactic, event["eventName"], "query")) & 0xFFFFFFFF,
        "definition": {
            "title": event["eventName"], "title_size": "16", "title_align": "left",
            "type": "query_value",
            "requests": [{
                "response_format": "scalar",
                "queries": [{
                    "data_source": "logs", "name": "query1", "indexes": ["*"],
                    "compute": {"aggregation": "count"},
                    "search": {"query": f"source:cloudtrail @evt.name:{event['eventName']} $userIdentity.arn $network.client.ip $account"},
                }],
                "formulas": [{"formula": "query1"}],
            }],
            "autoscale": True, "precision": 2,
        },
        "layout": {"x": x + 2, "y": y, "width": 2, "height": 2},
    }
    return [note, query]


def _dd_create_tactic_group_widgets(tactic, events):
    widgets = []
    x, y = 0, 0
    for event in events:
        if x + 4 > 12:
            x, y = 0, y + 2
        widgets.extend(_dd_tactic_widgets(event, tactic, x, y))
        x += 4
    return widgets, y + 2


def _generate_datadog_dashboard(events, filter_tactics=None, wild_only=False):
    if wild_only:
        events = [e for e in events if e.get("usedInWild", False)]

    tactics = _group_events_by_tactics(events, filter_tactics)
    exploited = _exploited_event_names(events)

    dashboard = _dd_base()
    dashboard["widgets"].append(_dd_logo())

    overview = [_dd_timeline(tactics), _dd_top_ten(exploited)]
    dashboard["widgets"].append({
        "id": 8265946211738038,
        "definition": {
            "type": "group", "layout_type": "ordered",
            "background_color": "blue", "title": "Overview", "show_title": True,
            "widgets": overview,
        },
        "layout": {"x": 6, "y": 0, "width": 6, "height": 5},
    })

    dashboard["widgets"].append(_dd_description())

    y_pos = 5
    for tactic, tevents in sorted(tactics.items(), key=lambda x: TACTIC_ORDER.get(x[0], 999)):
        group_widgets, row_h = _dd_create_tactic_group_widgets(tactic, tevents)
        dashboard["widgets"].append({
            "id": hash(tactic) & 0xFFFFFFFF,
            "definition": {
                "type": "group", "layout_type": "ordered",
                "background_color": "blue", "title": tactic, "show_title": True,
                "widgets": group_widgets,
            },
            "layout": {"x": 0, "y": y_pos, "width": 12, "height": row_h + 2},
        })
        y_pos += row_h + 2

    with open(DASHBOARD_JSON, "w", encoding="utf-8") as fh:
        json.dump(dashboard, fh, indent=4)
        fh.write("\n")
    print(f"  ✓ Generated {os.path.relpath(DASHBOARD_JSON, ROOT_DIR)}")


# --- ATT&CK index and Navigator layer (Insights page) -------------------

# Enterprise tactics in ATT&CK matrix order.
ATTACK_TACTIC_ORDER = [
    "TA0043", "TA0042", "TA0001", "TA0002", "TA0003", "TA0004", "TA0005",
    "TA0006", "TA0007", "TA0008", "TA0009", "TA0011", "TA0010", "TA0040",
]
# Accepts "T1098 - Name" and the variants found in the data ("T1078.004: Name", "T1562.001 Name").
ATTACK_ID_RE = re.compile(r"^\s*(TA?\d{4}(?:\.\d{3})?)\b")


def _attack_ids(values):
    ids = []
    for value in values:
        match = ATTACK_ID_RE.match(value)
        if match and match.group(1) not in ids:
            ids.append(match.group(1))
    return ids


def _attack_placements(events, lookup):
    """Place each event under (tactic, technique) pairs that ATT&CK itself lists.

    An event tagged with tactics A and B and technique T is counted under (A, T) only when
    ATT&CK lists T under A. Tagged tactics with no valid technique are reported as unplaced.
    """
    cells, unplaced, unknown = {}, {}, {}
    for event in events:
        event_id = f"{event['awsService']}-{event['eventName']}"
        tactics = _attack_ids(event.get("mitreAttackTactics", []))
        techniques = _attack_ids(event.get("mitreAttackTechniques", []) + event.get("mitreAttackSubTechniques", []))
        placed = set()
        for technique in techniques:
            info = lookup["techniques"].get(technique)
            if not info:
                unknown.setdefault(technique, []).append(event_id)
                continue
            for tactic in tactics:
                if tactic in info["tactics"]:
                    cells.setdefault((tactic, technique), []).append(event_id)
                    placed.add(tactic)
        for tactic in tactics:
            if tactic not in placed:
                unplaced.setdefault(tactic, []).append(event_id)
    return cells, unplaced, unknown


def _generate_attack_files(events: List[dict]):
    with open(ATTACK_LOOKUP, "r", encoding="utf-8") as fh:
        lookup = json.load(fh)
    with open(EVENTS_JSON, "rb") as fh:
        data_version = hashlib.sha256(fh.read()).hexdigest()[:12]

    cells, unplaced, unknown = _attack_placements(events, lookup)
    order = {tactic: i for i, tactic in enumerate(ATTACK_TACTIC_ORDER)}
    cell_keys = sorted(cells, key=lambda k: (order.get(k[0], 99), k[1]))

    used = {technique for _, technique in cells}
    used |= {technique.split(".")[0] for technique in used}
    index = {
        "attackVersion": ATTACK_VERSION,
        "dataVersion": data_version,
        "tactics": [{"id": t, **lookup["tactics"][t]} for t in ATTACK_TACTIC_ORDER if t in lookup["tactics"]],
        "techniques": {
            t: {"name": lookup["techniques"][t]["name"], "parent": t.split(".")[0] if "." in t else None}
            for t in sorted(used) if t in lookup["techniques"]
        },
        "cells": [{"tactic": k[0], "technique": k[1], "events": sorted(cells[k])} for k in cell_keys],
        "unplaced": [{"tactic": t, "events": sorted(unplaced[t])} for t in sorted(unplaced, key=lambda t: order.get(t, 99))],
        "unknownTechniques": [{"technique": t, "events": sorted(ids)} for t, ids in sorted(unknown.items())],
    }
    with open(ATTACK_INDEX_JSON, "w", encoding="utf-8") as fh:
        json.dump(index, fh, indent=1)
        fh.write("\n")

    # Presence-only ATT&CK Navigator layer: no scores, because counts reflect how the catalogue
    # was curated, not how often attackers use a technique.
    wild = {f"{e['awsService']}-{e['eventName']}" for e in events if e.get("usedInWild")}
    has_subtechniques = {(k[0], k[1].split(".")[0]) for k in cell_keys if "." in k[1]}
    techniques = []
    for tactic, technique in cell_keys:
        ids = sorted(cells[(tactic, technique)])
        in_wild = sum(1 for i in ids if i in wild)
        techniques.append({
            "techniqueID": technique,
            "tactic": lookup["tactics"][tactic]["shortname"],
            "color": "#8ECAE6",
            "comment": f"{len(ids)} catalogued CloudTrail event{'s' if len(ids) != 1 else ''} in TrailDiscover ({in_wild} seen in the wild)",
            "enabled": True,
            "metadata": [{"name": "Events", "value": ", ".join(ids)}],
            "links": [{"label": "Open in TrailDiscover", "url": f"{SITE_URL}?technique={technique}&tactic={tactic}"}],
            "showSubtechniques": (tactic, technique) in has_subtechniques,
        })
    layer = {
        "name": "TrailDiscover: catalogued CloudTrail events",
        "versions": {"attack": ATTACK_VERSION.split(".")[0], "navigator": "5.1.0", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": (
            "ATT&CK techniques that TrailDiscover maps catalogued AWS CloudTrail API calls to. "
            "Presence only: it does not show how often attackers use a technique, risk, or detection coverage. "
            f"Generated from events.json (data version {data_version}), ATT&CK v{ATTACK_VERSION}."
        ),
        "sorting": 0,
        "layout": {"layout": "side", "showID": True, "showName": True, "showAggregateScores": False, "countUnscored": False},
        "hideDisabled": False,
        "techniques": techniques,
        "gradient": {"colors": ["#ffffff", "#8ECAE6"], "minValue": 0, "maxValue": 1},
        "legendItems": [{"label": "Catalogued in TrailDiscover", "color": "#8ECAE6"}],
        "metadata": [{"name": "Source", "value": f"{SITE_URL}insights.html#techniques"}],
        "links": [{"label": "TrailDiscover Insights", "url": f"{SITE_URL}insights.html#techniques"}],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#023047",
        "selectTechniquesAcrossTactics": False,
        "selectSubtechniquesWithParent": False,
    }
    with open(ATTACK_LAYER_JSON, "w", encoding="utf-8") as fh:
        json.dump(layer, fh, indent=1)
        fh.write("\n")
    print(f"  ✓ Generated {os.path.relpath(ATTACK_INDEX_JSON, ROOT_DIR)} and "
          f"{os.path.relpath(ATTACK_LAYER_JSON, ROOT_DIR)} ({len(cell_keys)} tactic/technique cells, ATT&CK v{ATTACK_VERSION})")
    for technique, ids in sorted(unknown.items()):
        print(f"  ! {technique} is not an active technique in ATT&CK v{ATTACK_VERSION}: {', '.join(ids)}")


def step_generate(filter_tactics=None, wild_only=False):
    """Generate events.json, events.csv, datadog_dashboard.json and the ATT&CK files."""
    print("\n[ Step 4/4 ] Generating output files …")
    events = _load_all_events()
    _generate_events_json(events)
    _generate_events_csv(events)
    _generate_datadog_dashboard(events, filter_tactics=filter_tactics, wild_only=wild_only)
    _generate_attack_files(events)


# =====================================================================
# CLI
# =====================================================================

ALL_STEPS = ["format", "redact", "copy-logs", "generate"]


def main():
    parser = argparse.ArgumentParser(
        description="TrailDiscover build pipeline – format, redact, copy, and generate all outputs.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--steps", nargs="+", choices=ALL_STEPS, default=ALL_STEPS,
        help="Steps to run (default: all). Choices: format, redact, copy-logs, generate",
    )
    parser.add_argument(
        "--on-the-wild-only", action="store_true",
        help="Dashboard: include only events seen in the wild.",
    )
    parser.add_argument(
        "--tactics", nargs="+",
        help="Dashboard: filter to specific MITRE ATT&CK tactics.",
    )
    args = parser.parse_args()

    print("=" * 60)
    print("  TrailDiscover Build Pipeline")
    print("=" * 60)
    print(f"  Events dir : {EVENTS_DIR}")
    print(f"  Docs dir   : {DOCS_DIR}")
    print(f"  Steps      : {', '.join(args.steps)}")

    if "format" in args.steps:
        step_format()
    if "redact" in args.steps:
        step_redact()
    if "copy-logs" in args.steps:
        step_copy_logs()
    if "generate" in args.steps:
        step_generate(filter_tactics=args.tactics, wild_only=args.on_the_wild_only)

    print("\n" + "=" * 60)
    print("  ✅ Build complete!")
    print("=" * 60)


if __name__ == "__main__":
    main()
